### ISSUE TITLE
Panel administracyjny!

### ISSUE THREAD

**Issue by zalexstudios** [andrzuk/MyCMS#1]
Dlaczego panel administracyjny jest wyświetlany w ten sposób?
![2021-01-30_19h36_34](https://user-images.githubusercontent.com/2314551/106362225-bd471900-6332-11eb-8331-70b248011fe4.png)

**Comment by zalexstudios** [comment]
Install cms to localhost!

**Comment by andrzuk** [comment]
Sprawdź, czy style prawidłowo się ładują:

![fast-cms - style](https://user-images.githubusercontent.com/736561/106439176-b0800d80-6477-11eb-8532-b8111d7dd58d.png)

**Comment by andrzuk** [comment]
U mnie po wyłączeniu w konfiguracji następujących ustawień: options_panel_visible, menu_panel_visible, search_panel_visible, stats_panel_visible oraz facebook_panel_visible ekran Admin Panelu wygląda tak:

![fast-cms - admin panel](https://user-images.githubusercontent.com/736561/106439717-4a47ba80-6478-11eb-8a9b-a16245a4e54e.png)

**Comment by zalexstudios** [comment]
Ok! That's right!
![2021-02-01_12h28_15](https://user-images.githubusercontent.com/2314551/106439703-08734000-6489-11eb-9fc5-24662be4980c.png)
Thank you very much!

**Comment by andrzuk** [comment]
Great! Best regards! :)

**Comment by zalexstudios** [comment]
Czy jest wersja angielska?

**Comment by andrzuk** [comment]
Niestety, nie ma.

**Comment by zalexstudios** [comment]
Nie masz też wersji mobilnej?

**Comment by andrzuk** [comment]
Nie, mobilną (responsywną) zrobiłem w innym frameworku: https://github.com/andrzuk/microCMS oraz https://github.com/andrzuk/FineCMS poprawiona wersja: https://github.com/PrivateAccount/NotesCMS

**Comment by zalexstudios** [comment]
Brak dokumentów sekcji! Jak dodać?
----------------------------------------------
![docs](https://user-images.githubusercontent.com/2314551/106442915-f3001500-648c-11eb-87f7-d0b7f58d42dc.png)
![new](https://user-images.githubusercontent.com/2314551/106442927-f5fb0580-648c-11eb-9228-5633a90ed946.png)

**Comment by zalexstudios** [comment]
Czy to jest sekcja dotycząca dodawania wiadomości do witryny? A co to jest? Czy można dodawać wiadomości?

**Comment by andrzuk** [comment]
To jest sekcja dodawania dokumentów typu PDF, które chcemy osadzić na stronie. Dotyczy tylko pierwszego CMS-a.

**Comment by zalexstudios** [comment]
Czy możesz dodać do tej wersji? Dokumenty i aktualności? Ile to będzie kosztować?

**Comment by andrzuk** [comment]
Aktualności można dodawać w module Descriptions poz. Index (strona główna) - edytujemy za pomocą składni HTML.

**Comment by zalexstudios** [comment]
A co z sekcją dokumentów?

**Comment by andrzuk** [comment]
Ten CMS nie przewiduje takiej sekcji.

**Comment by zalexstudios** [comment]
DOBRZE! Dzięki! Użyję MyCMS, i przetłumaczę na język rosyjski i angielski.
